/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_glass_ui_gtk_GtkTray */

#ifndef _Included_com_sun_glass_ui_gtk_GtkTray
#define _Included_com_sun_glass_ui_gtk_GtkTray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_glass_ui_gtk_GtkTray
 * Method:    initTrayNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_sun_glass_ui_gtk_GtkTray_initTrayNative
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_glass_ui_gtk_GtkTray
 * Method:    addMenuNative
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_sun_glass_ui_gtk_GtkTray_addMenuNative
  (JNIEnv *, jobject, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
